title: as2built
description: Site statique BIM et Construction
permalink: /:title/
markdown: kramdown

# Ajoutez ceci pour forcer la page d'accueil à être le home-2
defaults:
  - scope:
      path: "" 
    values:
      home: true
      layout: "default"
